### PR TITLE
pricing plan card styling changed

### PR DESCRIPTION
**Pull request by anushkasinghal11**

### CODE REVIEW

**Comment by anushkasinghal11** [comment]
image

**Comment by Ayush7-BIT** [comment]
@anushkasinghal11 Everything is fine just keep it in order like the part which you have changed is used to be in white background-color, kindly see that otherwise everything will be effected.

**Comment by anushkasinghal11** [comment]
Which part? I didn't understand

**Comment by Ayush7-BIT** [comment]
I was just saying like keep background-color of website in order, like in this part it is white so kindly keep it in that order only if possible..else everything is fine

**Comment by anushkasinghal11** [comment]
image
I have made the changes. Kindly check @Ayush7-BIT

**Comment by sanyajain26** [comment]
I would like to work on it, kindly assign it to me.

**Comment by Ayush7-BIT** [comment]
Kindly resolve the conflicts @sanyajain26

**Comment by anushkasinghal11** [comment]
@Ayush7-BIT  Please check now. I have resolved the conflicts.

**Pull request merged**
